import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Hero from "../components/hero";
import Header from "../components/layouts/header";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-mono">
       <Header/>
       <Hero/>
      </main>
    </>
  );
};

export default Home;
